# country_codes.py

# -*- coding: utf-8 -*-

# value = unique 'Name (+code)' so each country round-trips on edit;
# label keeps the flag for the dropdown display.
COUNTRY_CODE_CHOICES = [
    ('Antigua and Barbuda (+1)', '🇦🇬 Antigua and Barbuda (+1)'),
    ('Barbados (+1)', '🇧🇧 Barbados (+1)'),
    ('Bahamas (+1)', '🇧🇸 Bahamas (+1)'),
    ('Canada (+1)', '🇨🇦 Canada (+1)'),
    ('Dominican Republic (+1)', '🇩🇴 Dominican Republic (+1)'),
    ('Grenada (+1)', '🇬🇩 Grenada (+1)'),
    ('Guam (+1)', '🇬🇺 Guam (+1)'),
    ('Jamaica (+1)', '🇯🇲 Jamaica (+1)'),
    ('Saint Lucia (+1)', '🇱🇨 Saint Lucia (+1)'),
    ('Puerto Rico (+1)', '🇵🇷 Puerto Rico (+1)'),
    ('Trinidad and Tobago (+1)', '🇹🇹 Trinidad and Tobago (+1)'),
    ('United States (+1)', '🇺🇸 United States (+1)'),
    ('Saint Vincent and the Grenadines (+1)', '🇻🇨 Saint Vincent and the Grenadines (+1)'),
    ('Egypt (+20)', '🇪🇬 Egypt (+20)'),
    ('Morocco (+212)', '🇲🇦 Morocco (+212)'),
    ('Algeria (+213)', '🇩🇿 Algeria (+213)'),
    ('Tunisia (+216)', '🇹🇳 Tunisia (+216)'),
    ('Ghana (+233)', '🇬🇭 Ghana (+233)'),
    ('Nigeria (+234)', '🇳🇬 Nigeria (+234)'),
    ('Sudan (+249)', '🇸🇩 Sudan (+249)'),
    ('Ethiopia (+251)', '🇪🇹 Ethiopia (+251)'),
    ('Kenya (+254)', '🇰🇪 Kenya (+254)'),
    ('Tanzania, United Republic of (+255)', '🇹🇿 Tanzania, United Republic of (+255)'),
    ('Uganda (+256)', '🇺🇬 Uganda (+256)'),
    ('South Africa (+27)', '🇿🇦 South Africa (+27)'),
    ('Greece (+30)', '🇬🇷 Greece (+30)'),
    ('Netherlands (+31)', '🇳🇱 Netherlands (+31)'),
    ('Belgium (+32)', '🇧🇪 Belgium (+32)'),
    ('France (+33)', '🇫🇷 France (+33)'),
    ('Spain (+34)', '🇪🇸 Spain (+34)'),
    ('Portugal (+351)', '🇵🇹 Portugal (+351)'),
    ('Luxembourg (+352)', '🇱🇺 Luxembourg (+352)'),
    ('Ireland (+353)', '🇮🇪 Ireland (+353)'),
    ('Iceland (+354)', '🇮🇸 Iceland (+354)'),
    ('Malta (+356)', '🇲🇹 Malta (+356)'),
    ('Cyprus (+357)', '🇨🇾 Cyprus (+357)'),
    ('Finland (+358)', '🇫🇮 Finland (+358)'),
    ('Bulgaria (+359)', '🇧🇬 Bulgaria (+359)'),
    ('Hungary (+36)', '🇭🇺 Hungary (+36)'),
    ('Lithuania (+370)', '🇱🇹 Lithuania (+370)'),
    ('Latvia (+371)', '🇱🇻 Latvia (+371)'),
    ('Estonia (+372)', '🇪🇪 Estonia (+372)'),
    ('Armenia (+374)', '🇦🇲 Armenia (+374)'),
    ('Ukraine (+380)', '🇺🇦 Ukraine (+380)'),
    ('Serbia (+381)', '🇷🇸 Serbia (+381)'),
    ('Croatia (+385)', '🇭🇷 Croatia (+385)'),
    ('Slovenia (+386)', '🇸🇮 Slovenia (+386)'),
    ('Italy (+39)', '🇮🇹 Italy (+39)'),
    ('Romania (+40)', '🇷🇴 Romania (+40)'),
    ('Switzerland (+41)', '🇨🇭 Switzerland (+41)'),
    ('Czechia (+420)', '🇨🇿 Czechia (+420)'),
    ('Slovakia (+421)', '🇸🇰 Slovakia (+421)'),
    ('United Kingdom (+44)', '🇬🇧 United Kingdom (+44)'),
    ('Denmark (+45)', '🇩🇰 Denmark (+45)'),
    ('Sweden (+46)', '🇸🇪 Sweden (+46)'),
    ('Norway (+47)', '🇳🇴 Norway (+47)'),
    ('Poland (+48)', '🇵🇱 Poland (+48)'),
    ('Germany (+49)', '🇩🇪 Germany (+49)'),
    ('Belize (+501)', '🇧🇿 Belize (+501)'),
    ('Guatemala (+502)', '🇬🇹 Guatemala (+502)'),
    ('El Salvador (+503)', '🇸🇻 El Salvador (+503)'),
    ('Honduras (+504)', '🇭🇳 Honduras (+504)'),
    ('Nicaragua (+505)', '🇳🇮 Nicaragua (+505)'),
    ('Costa Rica (+506)', '🇨🇷 Costa Rica (+506)'),
    ('Panama (+507)', '🇵🇦 Panama (+507)'),
    ('Peru (+51)', '🇵🇪 Peru (+51)'),
    ('Mexico (+52)', '🇲🇽 Mexico (+52)'),
    ('Cuba (+53)', '🇨🇺 Cuba (+53)'),
    ('Argentina (+54)', '🇦🇷 Argentina (+54)'),
    ('Brazil (+55)', '🇧🇷 Brazil (+55)'),
    ('Chile (+56)', '🇨🇱 Chile (+56)'),
    ('Colombia (+57)', '🇨🇴 Colombia (+57)'),
    ('Venezuela, Bolivarian Republic of (+58)', '🇻🇪 Venezuela, Bolivarian Republic of (+58)'),
    ('Bolivia, Plurinational State of (+591)', '🇧🇴 Bolivia, Plurinational State of (+591)'),
    ('Ecuador (+593)', '🇪🇨 Ecuador (+593)'),
    ('Paraguay (+595)', '🇵🇾 Paraguay (+595)'),
    ('Uruguay (+598)', '🇺🇾 Uruguay (+598)'),
    ('Malaysia (+60)', '🇲🇾 Malaysia (+60)'),
    ('Australia (+61)', '🇦🇺 Australia (+61)'),
    ('Indonesia (+62)', '🇮🇩 Indonesia (+62)'),
    ('Philippines (+63)', '🇵🇭 Philippines (+63)'),
    ('New Zealand (+64)', '🇳🇿 New Zealand (+64)'),
    ('Thailand (+66)', '🇹🇭 Thailand (+66)'),
    ('Kazakhstan (+7)', '🇰🇿 Kazakhstan (+7)'),
    ('Russian Federation (+7)', '🇷🇺 Russian Federation (+7)'),
    ('Japan (+81)', '🇯🇵 Japan (+81)'),
    ('Korea, Republic of (+82)', '🇰🇷 Korea, Republic of (+82)'),
    ('Viet Nam (+84)', '🇻🇳 Viet Nam (+84)'),
    ('Cambodia (+855)', '🇰🇭 Cambodia (+855)'),
    ('Lao Peoples Democratic Republic (+856)', '🇱🇦 Lao Peoples Democratic Republic (+856)'),
    ('China (+86)', '🇨🇳 China (+86)'),
    ('Bangladesh (+880)', '🇧🇩 Bangladesh (+880)'),
    ('Turkey (+90)', '🇹🇷 Turkey (+90)'),
    ('India (+91)', '🇮🇳 India (+91)'),
    ('Pakistan (+92)', '🇵🇰 Pakistan (+92)'),
    ('Afghanistan (+93)', '🇦🇫 Afghanistan (+93)'),
    ('Sri Lanka (+94)', '🇱🇰 Sri Lanka (+94)'),
    ('Myanmar (+95)', '🇲🇲 Myanmar (+95)'),
    ('Maldives (+960)', '🇲🇻 Maldives (+960)'),
    ('Lebanon (+961)', '🇱🇧 Lebanon (+961)'),
    ('Jordan (+962)', '🇯🇴 Jordan (+962)'),
    ('Syrian Arab Republic (+963)', '🇸🇾 Syrian Arab Republic (+963)'),
    ('Iraq (+964)', '🇮🇶 Iraq (+964)'),
    ('Kuwait (+965)', '🇰🇼 Kuwait (+965)'),
    ('Saudi Arabia (+966)', '🇸🇦 Saudi Arabia (+966)'),
    ('Yemen (+967)', '🇾🇪 Yemen (+967)'),
    ('Oman (+968)', '🇴🇲 Oman (+968)'),
    ('Palestine, State of (+970)', '🇵🇸 Palestine, State of (+970)'),
    ('United Arab Emirates (+971)', '🇦🇪 United Arab Emirates (+971)'),
    ('Israel (+972)', '🇮🇱 Israel (+972)'),
    ('Bahrain (+973)', '🇧🇭 Bahrain (+973)'),
    ('Qatar (+974)', '🇶🇦 Qatar (+974)'),
    ('Bhutan (+975)', '🇧🇹 Bhutan (+975)'),
    ('Mongolia (+976)', '🇲🇳 Mongolia (+976)'),
    ('Nepal (+977)', '🇳🇵 Nepal (+977)'),
    ('Iran, Islamic Republic of (+98)', '🇮🇷 Iran, Islamic Republic of (+98)'),
    ('Tajikistan (+992)', '🇹🇯 Tajikistan (+992)'),
    ('Turkmenistan (+993)', '🇹🇲 Turkmenistan (+993)'),
    ('Azerbaijan (+994)', '🇦🇿 Azerbaijan (+994)'),
    ('Georgia (+995)', '🇬🇪 Georgia (+995)'),
    ('Kyrgyzstan (+996)', '🇰🇬 Kyrgyzstan (+996)'),
    ('Uzbekistan (+998)', '🇺🇿 Uzbekistan (+998)'),
]
