# Generated by Django 4.1 on 2024-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_meetingrequest_farmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
