# Generated by Django 4.1 on 2024-07-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_meetingrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='annual_throughput',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roaster',
            name='coffee_types_interested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='min_lot_size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roaster',
            name='origins_interested',
            field=models.TextField(blank=True, null=True),
        ),
    ]
