# Generated by Django 4.1 on 2024-07-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roaster_annual_throughput_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='affiliation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='annual_throughput',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='coffee_types_interested',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='min_lot_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='roaster',
            name='origins_interested',
            field=models.TextField(null=True),
        ),
    ]
