# Generated by Django 4.1 on 2024-07-17 03:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_addisactive"),
        ("base", "0005_alter_farmer_affiliation_alter_farmer_bio_and_more"),
    ]

    operations = []
