# Generated by Django 4.2.14 on 2024-08-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_farmer_size_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roaster',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='roaster_profiles/'),
        ),
    ]
