# Generated by Django 4.2.14 on 2024-08-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_roaster_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roaster',
            name='location',
        ),
        migrations.AddField(
            model_name='roaster',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
