# Generated by Django 4.1 on 2024-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_remove_farmer_size_remove_user_firstname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="farm_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="farm_size",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="firstname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="lastname",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
