# Generated by Django 4.2.14 on 2024-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_farmer_farm_name_alter_farmer_farm_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farmerphoto',
            name='order',
        ),
        migrations.RemoveField(
            model_name='roaster',
            name='location',
        ),
        migrations.RemoveField(
            model_name='roasterphoto',
            name='order',
        ),
        migrations.RemoveField(
            model_name='roasterphoto',
            name='profile',
        ),
        migrations.AddField(
            model_name='farmer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roaster',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='roaster_profiles/'),
        ),
        migrations.AddField(
            model_name='roaster',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='annual_production',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual production in tons', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size in hectares', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
