# Generated by Django 4.2.14 on 2024-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_roaster_location_roaster_city_roaster_country_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='farmer',
        #     name='location',
        # ),
        # migrations.AddField(
        #     model_name='farmer',
        #     name='city',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='farmer',
        #     name='country',
        #     field=models.CharField(max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='farmer',
        #     name='state',
        #     field=models.CharField(max_length=100, null=True),
        # ),
    ]
