# Generated by Django 4.2.14 on 2024-08-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_farmer_location_farmer_city_farmer_country_and_more'),
    ]

    operations = [
    #     migrations.AlterField(
    #         model_name='farmer',
    #         name='annual_production',
    #         field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual production in tons', max_digits=10, null=True),
    #     ),
    #     migrations.AlterField(
    #         model_name='farmer',
    #         name='city',
    #         field=models.CharField(blank=True, max_length=255, null=True),
    #     ),
    #     migrations.AlterField(
    #         model_name='farmer',
    #         name='country',
    #         field=models.CharField(blank=True, max_length=255, null=True),
    #     ),
    #     migrations.AlterField(
    #         model_name='farmer',
    #         name='farm_size',
    #         field=models.DecimalField(decimal_places=2, help_text='Size in hectares', max_digits=10),
    #     ),
    #     migrations.AlterField(
    #         model_name='farmer',
    #         name='state',
    #         field=models.CharField(blank=True, max_length=255, null=True),
    #     ),
    ]
