# Generated by Django 4.2.14 on 2024-08-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_farmer_annual_production_alter_farmer_city_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='farmer',
        #     name='location',
        # ),
        migrations.RemoveField(
            model_name='roasterphoto',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='roasterphoto',
            name='order',
        ),
    ]
