# Generated by Django 4.1 on 2025-01-16 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_language_farmer_annual_production_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("story_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        choices=[("English ", "English "), ("Spanish", "Spanish")],
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.language",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farmer_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
