# Generated by Django 4.1 on 2025-01-24 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_story"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="harvest_season",
        ),
        migrations.AlterField(
            model_name="story",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.language",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="harvest_season",
            field=models.ManyToManyField(
                blank=True,
                choices=[
                    ("spring", "spring"),
                    ("summer", "summer"),
                    ("autumn", "autumn"),
                    ("winter", "winter"),
                ],
                to="base.season",
            ),
        ),
    ]
