# Generated by Django 4.1 on 2025-01-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_season_remove_farmer_harvest_season_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingMethod",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="farmer",
            name="harvest_season",
            field=models.ManyToManyField(blank=True, to="base.season"),
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="processing_method",
        ),
        migrations.AddField(
            model_name="farmer",
            name="processing_method",
            field=models.ManyToManyField(blank=True, to="base.processingmethod"),
        ),
    ]
