# Generated by Django 4.1 on 2025-01-30 16:52

from django.db import migrations

HARVEST_CHOICES = [
   'Jan-Feb-Mar' ,
   'Apr-May-Jun' ,
   'Jul-Aug-Sep' ,
   'Oct-Nov-Dec', 
]

PROCESSING_METHOD_CHOICES = [
    'Washed',
    'Natural',
    'Honey',
    'Semi-Washed',
    'Controlled',
    'Anaerobic',
]

def create_processing_method(apps, schema_editor):
    ProcessingMethod = apps.get_model("base", "ProcessingMethod")
    for e in PROCESSING_METHOD_CHOICES:
        ProcessingMethod.objects.create(name=e)
    

def create_harvest_season(apps, schema_editor):
    Season = apps.get_model("base", "Season")
    for e in HARVEST_CHOICES:
        Season.objects.create(name=e)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_processingmethod_alter_farmer_harvest_season_and_more"),
    ]

    operations = [
        migrations.RunPython(create_processing_method),
        migrations.RunPython(create_harvest_season),
    ]
