# Generated by Django 4.1 on 2025-01-30 17:18

from django.db import migrations, models
import django.db.models.deletion

CUP_SCORES_CHOICES = [
    '0-80',
    '81-83',
    '84-86',
    '87-89',
    '90-100',
]

def create_cupscore(apps, schema_editor):
    CupScore = apps.get_model("base", "CupScore")
    for e in CUP_SCORES_CHOICES:
        CupScore.objects.create(name=e)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_auto_20250130_1652"),
    ]

    operations = [
        migrations.CreateModel(
            name="CupScore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="cup_scores_received",
        ),
        migrations.AlterField(
            model_name="story",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="story_languages",
                to="base.language",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="cup_scores_received",
            field=models.ManyToManyField(blank=True, null=True, to="base.cupscore"),
        ),
        migrations.RunPython(create_cupscore),
    ]
