# Generated by Django 4.1 on 2025-01-31 00:12

from django.db import migrations

LANGUAGE_CHOICES = [
    'English',
    'Spanish',
]

def create_languages(apps, schema_editor):
    Language = apps.get_model("base", "Language")
    for language in LANGUAGE_CHOICES:
        Language.objects.create(name=language)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_cupscore_remove_farmer_cup_scores_received_and_more"),
    ]

    operations = [
        migrations.RunPython(create_languages),
    ]
