# Generated by Django 4.1 on 2025-02-03 00:46

from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_auto_20250131_0012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.ProfileStorage(),
                upload_to="",
            ),
        ),
    ]
