# Generated by Django 4.1 on 2025-02-12 19:25

from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_alter_farmer_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="is_details_filled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="farmerphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.PhotoStorage(),
                upload_to="",
            ),
        ),
    ]
