# Generated by Django 4.1 on 2025-02-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_farmer_is_details_filled_alter_farmerphoto_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="is_member_organization",
            field=models.BooleanField(default=False),
        ),
    ]
