# Generated by Django 4.1 on 2025-02-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_farmer_is_member_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="member_organization_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="annual_production_unit",
            field=models.CharField(
                blank=True,
                choices=[("kilograms", "Kilograms")],
                default="kilograms",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="is_member_organization",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
