# Generated by Django 4.1 on 2025-03-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0024_buyerfunctions_roaster_coffee_purchase_involvement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaster",
            name="is_details_filled",
            field=models.BooleanField(default=False),
        ),
    ]
