# Generated by Django 4.1 on 2025-03-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_roaster_is_details_filled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roaster",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="coffee_types_interested",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="origins_interested",
            field=models.TextField(blank=True, null=True),
        ),
    ]
