# Generated by Django 4.1 on 2025-03-26 21:02

from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_alter_roaster_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roaster",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.ProfileStorageRoaster(),
                upload_to="",
            ),
        ),
    ]
