# Generated by Django 4.1 on 2025-03-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0027_alter_roaster_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="farmer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="farmer_stories",
                to="base.farmer",
            ),
        ),
    ]
