# Generated by Django 4.1 on 2026-02-09 14:44

from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0028_story_farmer"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="header_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_profile_storage,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="country_code",
            field=models.CharField(
                blank=True, default="US (+1)", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_profile_storage,
                upload_to="",
            ),
        ),
    ]
