# Generated by Django 4.1 on 2026-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0029_farmer_header_image_alter_farmer_country_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="farmer",
            name="main_roles",
            field=models.ManyToManyField(blank=True, to="base.role"),
        ),
    ]
