# Generated by Django 4.1 on 2026-02-12 19:27

from django.db import migrations


ROLES = ['Owner', 'Manager', 'Worker']

# Map old CharField values to Role names
ROLE_MAP = {
    'owner': 'Owner',
    'manager': 'Manager',
    'worker': 'Worker',
}


def create_roles_and_migrate(apps, schema_editor):
    Role = apps.get_model('base', 'Role')
    Farmer = apps.get_model('base', 'Farmer')

    # Create the Role objects
    role_objects = {}
    for role_name in ROLES:
        role, _ = Role.objects.get_or_create(name=role_name)
        role_objects[role_name] = role

    # Migrate existing main_role data to main_roles
    for farmer in Farmer.objects.exclude(main_role__isnull=True).exclude(main_role=''):
        role_name = ROLE_MAP.get(farmer.main_role)
        if role_name and role_name in role_objects:
            farmer.main_roles.add(role_objects[role_name])


def reverse_migration(apps, schema_editor):
    Role = apps.get_model('base', 'Role')
    Farmer = apps.get_model('base', 'Farmer')

    # Copy first main_roles value back to main_role
    for farmer in Farmer.objects.all():
        first_role = farmer.main_roles.first()
        if first_role:
            farmer.main_role = first_role.name.lower()
            farmer.save()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0030_role_farmer_main_roles"),
    ]

    operations = [
        migrations.RunPython(create_roles_and_migrate, reverse_migration),
    ]
