# Generated by Django 4.1 on 2026-02-12

from django.db import migrations


NEW_ROLES = ['Tenant', 'Employee', 'Farm Manager', 'Business Manager']


def update_roles(apps, schema_editor):
    Role = apps.get_model('base', 'Role')
    Farmer = apps.get_model('base', 'Farmer')

    # Create new roles
    new_role_objects = {}
    for role_name in NEW_ROLES:
        role, _ = Role.objects.get_or_create(name=role_name)
        new_role_objects[role_name] = role

    # Split "Manager" into "Farm Manager" and "Business Manager"
    old_manager = Role.objects.filter(name='Manager').first()
    if old_manager:
        farm_mgr = new_role_objects['Farm Manager']
        biz_mgr = new_role_objects['Business Manager']
        for farmer in Farmer.objects.filter(main_roles=old_manager):
            farmer.main_roles.add(farm_mgr, biz_mgr)
            farmer.main_roles.remove(old_manager)
        old_manager.delete()


def reverse_roles(apps, schema_editor):
    Role = apps.get_model('base', 'Role')
    Farmer = apps.get_model('base', 'Farmer')

    # Recreate Manager
    manager, _ = Role.objects.get_or_create(name='Manager')

    # Merge Farm Manager / Business Manager back to Manager
    farm_mgr = Role.objects.filter(name='Farm Manager').first()
    biz_mgr = Role.objects.filter(name='Business Manager').first()
    mgr_roles = [r for r in [farm_mgr, biz_mgr] if r]
    for role in mgr_roles:
        for farmer in Farmer.objects.filter(main_roles=role):
            farmer.main_roles.add(manager)
            farmer.main_roles.remove(role)
        role.delete()

    # Remove new roles
    Role.objects.filter(name__in=['Tenant', 'Employee']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0031_migrate_main_role_data"),
    ]

    operations = [
        migrations.RunPython(update_roles, reverse_roles),
    ]
