# Generated by Django 4.2.21 on 2026-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0032_update_role_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
