# Generated by Django 4.2.21 on 2026-03-06 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("update_profile", "Updated profile"),
                            ("update_status", "Updated status"),
                            ("upload_photo", "Uploaded photo"),
                            ("delete_photo", "Deleted photo"),
                            ("add_story", "Added story"),
                            ("update_story", "Updated story"),
                            ("publish_profile", "Published profile"),
                            ("request_meeting", "Requested meeting"),
                            ("manage_meeting", "Managed meeting request"),
                            ("create_account", "Created account"),
                            ("create_admin", "Created admin"),
                            ("toggle_admin", "Toggled admin access"),
                            ("complete_details", "Completed profile details"),
                            ("update_header", "Updated header image"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
