# Generated by Django 4.2.21 on 2026-03-24 19:13

from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0034_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaster",
            name="header_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.ProfileStorageRoaster(),
                upload_to="",
            ),
        ),
    ]
