# Generated by Django 4.2.21 on 2026-04-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0037_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaster",
            name="country_code",
            field=models.CharField(
                blank=True, default="US (+1)", max_length=255, null=True
            ),
        ),
    ]
