# Generated by Django 4.2.21 on 2026-05-07 14:25

from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0039_seed_coffee_pricing_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roasterphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.PhotoStorage(),
                upload_to="",
            ),
        ),
    ]
