# Generated by Django 4.2.21 on 2026-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0040_alter_roasterphoto_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingrequest",
            name="proposed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
