# Generated by Django 4.2.21 on 2026-05-19 22:19

from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0042_conversation_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_photo_storage,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="header_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_roaster_profile_storage,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_roaster_profile_storage,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="roasterphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_photo_storage,
                upload_to="",
            ),
        ),
    ]
