# Generated by Django 4.2.21 on 2026-06-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0043_alter_farmerphoto_photo_alter_roaster_header_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaster",
            name="sourcing_prefs_filled",
            field=models.BooleanField(default=False),
        ),
    ]
