# Generated by Django 4.2.21 on 2026-06-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0044_roaster_sourcing_prefs_filled"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaster",
            name="cup_scores_interested",
            field=models.ManyToManyField(
                blank=True, related_name="interested_roasters", to="base.cupscore"
            ),
        ),
    ]
