# Generated by Django 4.2.21 on 2026-06-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0050_forummeeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="forummeeting",
            name="invite_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="forummeeting",
            name="meeting_link",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
