# Generated by Django 4.2.30 on 2026-07-12 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("base", "0051_forummeeting_invite_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("view_profile", "Viewed profile"),
                            ("view_story", "Viewed story"),
                            ("send_message", "Sent message"),
                            ("request_connection", "Requested connection"),
                            ("accept_connection", "Accepted connection"),
                            ("decline_connection", "Declined connection"),
                            ("request_meeting", "Proposed meeting"),
                        ],
                        max_length=32,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_events_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="base_intera_event_t_65f2e7_idx",
                    ),
                    models.Index(
                        fields=["target_user", "event_type"],
                        name="base_intera_target__40c232_idx",
                    ),
                    models.Index(
                        fields=["actor", "event_type"],
                        name="base_intera_actor_i_613d92_idx",
                    ),
                ],
            },
        ),
    ]
