# Generated by Django 4.2.30 on 2026-07-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0052_interactionevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="country_code",
            field=models.CharField(
                blank=True, default="United States (+1)", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="country_code",
            field=models.CharField(
                blank=True, default="United States (+1)", max_length=255, null=True
            ),
        ),
    ]
