# Generated by Django 4.2.30 on 2026-08-05 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0055_adminemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("profile_edit", "Profile edit"),
                            ("story", "Story"),
                            ("photo", "Photo"),
                            ("picture", "Profile picture"),
                            ("header", "Header image"),
                            ("admin", "Admin edit"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="interactionevent",
            name="base_intera_event_t_65f2e7_idx",
        ),
        migrations.RemoveIndex(
            model_name="interactionevent",
            name="base_intera_target__40c232_idx",
        ),
        migrations.RemoveIndex(
            model_name="interactionevent",
            name="base_intera_actor_i_613d92_idx",
        ),
        migrations.RemoveField(
            model_name="interactionevent",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="interactionevent",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="interactionevent",
            name="object_id",
        ),
        migrations.AddField(
            model_name="interactionevent",
            name="path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="interactionevent",
            name="session_key",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="interactionevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="interactionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Logged in"),
                    ("profile_view", "Viewed profile"),
                    ("story_view", "Viewed story"),
                    ("connection_request", "Sent connection request"),
                    ("connection_accepted", "Accepted connection"),
                    ("connection_declined", "Declined connection"),
                    ("meeting_proposed", "Proposed meeting"),
                    ("message_sent", "Sent message"),
                    ("resource_view", "Viewed resource"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interactionevent",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profilechange",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="profilechange",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
