# Generated by Django 4.2.30 on 2026-08-12 18:55

import base.validators
from django.db import migrations, models
import rbf_platform.storage_backends


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0056_profilechange_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="header_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_profile_storage,
                upload_to="",
                validators=[base.validators.validate_uploaded_image],
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_profile_storage,
                upload_to="",
                validators=[base.validators.validate_uploaded_image],
            ),
        ),
        migrations.AlterField(
            model_name="farmerphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_photo_storage,
                upload_to="",
                validators=[base.validators.validate_uploaded_image],
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="resources/",
                validators=[base.validators.validate_uploaded_image],
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="header_image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_roaster_profile_storage,
                upload_to="",
                validators=[base.validators.validate_uploaded_image],
            ),
        ),
        migrations.AlterField(
            model_name="roaster",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_roaster_profile_storage,
                upload_to="",
                validators=[base.validators.validate_uploaded_image],
            ),
        ),
        migrations.AlterField(
            model_name="roasterphoto",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=rbf_platform.storage_backends.get_photo_storage,
                upload_to="",
                validators=[base.validators.validate_uploaded_image],
            ),
        ),
    ]
