# Generated by Django 4.2.30 on 2026-08-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0057_alter_farmer_header_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
