# Generated by Django 4.2.30 on 2026-09-16 16:14

from django.db import migrations, models


def publish_existing_profiles(apps, schema_editor):
    """Publish everyone who is discoverable today, so deploy changes nothing.

    Until now ``is_profile_published`` gated nothing: farmers were browsable as
    soon as they had a story, roasters as soon as their details were filled.
    Now that ``discoverable()`` checks the flag, the users who are already live
    have to be backfilled or they would all disappear at once.
    """
    Farmer = apps.get_model('base', 'Farmer')
    Roaster = apps.get_model('base', 'Roaster')

    # Materialise the ids first: MySQL cannot UPDATE a table referenced by a
    # subquery in the same statement, and the story filter spans a join.
    farmer_ids = list(
        Farmer.objects.filter(farmer_stories__isnull=False)
        .values_list('pk', flat=True).distinct()
    )
    Farmer.objects.filter(pk__in=farmer_ids).update(is_profile_published=True)
    Roaster.objects.filter(is_details_filled=True).update(is_profile_published=True)


def unpublish_all(apps, schema_editor):
    """Reverse: return both models to the pre-backfill default."""
    apps.get_model('base', 'Farmer').objects.update(is_profile_published=False)
    apps.get_model('base', 'Roaster').objects.update(is_profile_published=False)


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0058_user_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="roaster",
            name="is_profile_published",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(publish_existing_profiles, unpublish_all),
    ]
