# Generated by Django 4.2.30 on 2026-09-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0059_roaster_is_profile_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interactionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login", "Logged in"),
                    ("profile_view", "Viewed profile"),
                    ("story_view", "Viewed story"),
                    ("connection_request", "Sent connection request"),
                    ("connection_accepted", "Accepted connection"),
                    ("connection_declined", "Declined connection"),
                    ("connection_withdrawn", "Withdrew connection request"),
                    ("connection_disconnected", "Disconnected"),
                    ("meeting_proposed", "Proposed meeting"),
                    ("message_sent", "Sent message"),
                    ("resource_view", "Viewed resource"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
